### ISSUE TITLE
Algunos candidatos tiene mal el cargo

### ISSUE THREAD

**Issue by martinszy** [YoQuieroSaber/dinescrap#2]
Ejemplo, en el CSV de Santa Fe:
https://github.com/YoQuieroSaber/dinescrap/blob/master/salida/SANTA%20FE.csv

"SANTA FE   PARLAMENTARIO MERCOSUR DISTRITO REGIONAL SUPLENTE   TELPUK, MARIA LUJAN     2"

Pero en el PDF
http://www.elecciones.gov.ar/admin/ckfinder/userfiles/files/SANTA%20FE.pdf

"503  ALIANZA COMPROMISO FEDERAL, LISTA: 2B DESARROLLO AGRO INDUSTRIAL. SENADOR NACIONAL TITULAR
1. GRANELLI, JUAN JAVIER
2. TELPUK, MARIA LUJAN"

Está mal el cargo, que debe ser senador y es parlamentario. Lo tomó del cargo anteiror que si era parlamentario.

**Comment by Nullpo** [comment]
A simple vista, el problema parece estár en el formato del archivo que devuelve el pdf.

La linea donde comienza el cargo de Senador nacional titular es:

```
 \f503 - ALIANZA COMPROMISO FEDERAL, LISTA: 2B - DESARROLLO AGRO INDUSTRIAL. SENADOR NACIONAL TITULAR
```

Ese "\f" hace que no se esté parseando bien la nueva categoría (GRANELLI también aparece como parlamentario del mercosur). Ahora estoy chequeando un poco que lo demás funcione ok. Lo subo y si podés, hacele un chequeo a los datos :)
